from ..utils.llm import call_llm
from ..utils.extract import extract_tagged_code


def refactor_code(code: str) -> str:
    """Ask the LLM to refactor the code for readability and efficiency."""
    print("\n[5] Refactoring for Performance and Style...")

    messages = [
        {
            "role": "system",
            "content": (
                "You are a Senior Python Developer. \n"
                "Output ONLY the Python function wrapped between <function> and </function>. \n"
                "No explanations. Validate that exactly one <function> block is present."
            )
        },
        {
            "role": "user",
            "content": f"Refactor this code for efficiency and readability:\n{code}"
        }
    ]

    refined_code = call_llm(messages)
    code = extract_tagged_code(refined_code)
    if code is None:
        raise ValueError("No valid code was generated by the Refactor Agent")
    print("Raw, refined code:\n", refined_code)
    print("Extracted from tags:\n", code)
    return code